"""create initial models

Revision ID: 001_initial
Revises: 
Create Date: 2026-03-23 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mot_de_passe', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('qr_code_token', sa.String(), nullable=True),
    sa.Column('qr_code_expiry', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_qr_code_token'), 'users', ['qr_code_token'], unique=True)

    op.create_table('horaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jour_semaine', sa.Integer(), nullable=True),
    sa.Column('heure_debut', sa.Time(), nullable=True),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('est_exception', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horaires_id'), 'horaires', ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('est_lu', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)

    op.create_table('presences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_pointage', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('heure_arrivee', sa.Time(), nullable=True),
    sa.Column('heure_depart', sa.Time(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('type_pointage', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presences_id'), 'presences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presences_id'), table_name='presences')
    op.drop_table('presences')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_horaires_id'), table_name='horaires')
    op.drop_table('horaires')
    op.drop_index(op.f('ix_users_qr_code_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
